/* eslint-disable prettier/prettier */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

type ComponentRegistry = Record<
  string,
  Record<
    string,
    {
      name: string
      story: string
      component: string
      file: string
    }
  >
>

export const Index: ComponentRegistry = {
  "breadcrumbs": {
    "default": {
      name: "breadcrumbs-default",
      story: "default",
      component: React.lazy(() => import("@/registry/breadcrumbs/default")),
      file: "registry/breadcrumbs/default.tsx"
    },
    "icon": {
      name: "breadcrumbs-icon",
      story: "icon",
      component: React.lazy(() => import("@/registry/breadcrumbs/icon")),
      file: "registry/breadcrumbs/icon.tsx"
    },
  },
};
