/* eslint-disable prettier/prettier */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

type ComponentRegistry = Record<
  string,
  Record<
    string,
    {
      name: string
      story: string
      component: string
      file: string
    }
  >
>

export const Index: ComponentRegistry = {
  "badge": {
    "colors": {
      name: "badge-colors",
      story: "colors",
      component: React.lazy(() => import("@/registry/badge/colors")),
      file: "registry/badge/colors.tsx"
    },
    "default": {
      name: "badge-default",
      story: "default",
      component: React.lazy(() => import("@/registry/badge/default")),
      file: "registry/badge/default.tsx"
    },
  },
  "breadcrumbs": {
    "default": {
      name: "breadcrumbs-default",
      story: "default",
      component: React.lazy(() => import("@/registry/breadcrumbs/default")),
      file: "registry/breadcrumbs/default.tsx"
    },
    "icon": {
      name: "breadcrumbs-icon",
      story: "icon",
      component: React.lazy(() => import("@/registry/breadcrumbs/icon")),
      file: "registry/breadcrumbs/icon.tsx"
    },
  },
  "checkbox": {
    "default": {
      name: "checkbox-default",
      story: "default",
      component: React.lazy(() => import("@/registry/checkbox/default")),
      file: "registry/checkbox/default.tsx"
    },
    "disabled": {
      name: "checkbox-disabled",
      story: "disabled",
      component: React.lazy(() => import("@/registry/checkbox/disabled")),
      file: "registry/checkbox/disabled.tsx"
    },
    "intermediate": {
      name: "checkbox-intermediate",
      story: "intermediate",
      component: React.lazy(() => import("@/registry/checkbox/intermediate")),
      file: "registry/checkbox/intermediate.tsx"
    },
    "invalid": {
      name: "checkbox-invalid",
      story: "invalid",
      component: React.lazy(() => import("@/registry/checkbox/invalid")),
      file: "registry/checkbox/invalid.tsx"
    },
  },
  "tabs": {
    "default": {
      name: "tabs-default",
      story: "default",
      component: React.lazy(() => import("@/registry/tabs/default")),
      file: "registry/tabs/default.tsx"
    },
    "disabled-keys": {
      name: "tabs-disabled-keys",
      story: "disabled-keys",
      component: React.lazy(() => import("@/registry/tabs/disabled-keys")),
      file: "registry/tabs/disabled-keys.tsx"
    },
    "disabled": {
      name: "tabs-disabled",
      story: "disabled",
      component: React.lazy(() => import("@/registry/tabs/disabled")),
      file: "registry/tabs/disabled.tsx"
    },
    "vertical": {
      name: "tabs-vertical",
      story: "vertical",
      component: React.lazy(() => import("@/registry/tabs/vertical")),
      file: "registry/tabs/vertical.tsx"
    },
  },
};
